[package]
name = "rsn"
version = "0.1.0"
author = "Isse"
keywords = ["parser", "deserialization"]
repository = "https://github.com/IsseW/rsn"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl-trait-for-tuples = "0.2.2"
arrayvec = "0.7"
indexmap = "2.2.6"

vek = { version = "0.17", optional = true }
hashbrown = { version = "0.14", optional = true }

rsn_derive = { path = "../rsn_derive", optional = true }
rsn_parser.path = "../rsn_parser"

[features]
default = ["derive", "impl_vek", "impl_hashbrown"]
impl_vek = ["vek"]
impl_hashbrown = ["hashbrown"]
derive = ["rsn_derive"]
